INSERT INTO ROLE(name) VALUES ('ROLE_USER');
INSERT INTO ROLE(name) VALUES ('ROLE_ADMIN');
INSERT INTO USER(USERNAME, PASSWORD) VALUES ('admin', '{bcrypt}$2a$10$nl7pSPYD7np429fWpfqcKu3WKzljgMgF7vdMk4BfVVWmVHTThmOS2');
INSERT INTO USER_ROLES (USERS_USERNAME, ROLES_ID) VALUES ('admin', 2);